### PR TITLE
initiate repo and update the data.py adapt audio-text

### PR DESCRIPTION
**Pull request by tianyu-z**

### CODE REVIEW

**Comment by tianyu-z** [comment]
A quick way to test it

```
import sys
import training.data as data
from easydict import EasyDict as edict

args = edict()
args.train_data = ["/media/work/easystore1/clotho/test_{}.tar".format(i) for i in range(16)] # all the training tar files
args.val_data = "/media/work/DATA/dataset/Clotho/train/sample1.tar" # the validation tar files
args.distributed = False
args.world_size = 1 # GPU number
args.batch_size = 6 # got issue when set larger than 1
args.workers = 3 # number of CPU for data loader
args.seed = 100 # random seed

import os
os.environ["WDS_EPOCH"] = str(10)
dl = data.get_wds_dataset(args, True).dataloader # True means train

if __name__=="__main__":
	for i, batch in enumerate(dl):
		print(i, batch)
```

**Comment by rom1504** [comment]
Are you really sure you want to duplicate open clip instead of making it more general?

**Comment by tianyu-z** [comment]
Hi, sorry for the late reply. (I actually replied by email but somehow didn't show up here)
Right, this is the repo that we start from. We will definitely make more changes in the future. I updated `https://github.com/LAION-AI/CLAP/tree/main/src/training/data.py ` from line 162 to 311

**Comment by lukewys** [comment]
> Are you really sure you want to duplicate open clip instead of making it more general?

We are building on Open-CLIP code base such that it will be easy for us to incorporate future updates on other modalities or connecting with other CLIPs trained in LAION.
 
This first PR is just about updating the dataloader. We are adding the audio encoder.

**Comment by rom1504** [comment]
Yes my point was not that you shouldn't use openclip code but rather the opposite: you could consider directly using openclip code and bringing your improvements and changes directly there.

**Comment by lukewys** [comment]
Yeah that is a good point! But we were afraid that we will make things messy for the vision part. So we will probably consider PR to open-CLIP after we developed our model into some milestone in the future.

**Comment by tianyu-z** [comment]
This is just the first step. We will have other changes later. I hope
initiate the code here does not hurt.

My modification is in data.py. Please feel free to review.

**Pull request merged**
